# Generated by Django 4.2 on 2024-11-02 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mc', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('rep_name', models.CharField(max_length=100)),
                ('rep_ph_number', models.CharField(max_length=100)),
                ('rep_email', models.EmailField(max_length=254)),
                ('billing_email', models.EmailField(max_length=254)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
                'db_table': 'brokers',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=25)),
                ('zipcode', models.CharField(max_length=100)),
                ('ph_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('note', models.TextField(blank=True, null=True)),
                ('working_hours', models.TextField(blank=True, null=True)),
                ('need_appointment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=100)),
                ('shipment', models.CharField(max_length=100)),
                ('load_number', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('driver_pay', models.DecimalField(decimal_places=2, max_digits=20)),
                ('carrier_pay', models.DecimalField(decimal_places=2, max_digits=20)),
                ('smf_pay', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pickup_date', models.DateField()),
                ('drop_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to=settings.AUTH_USER_MODEL)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.broker')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.driver')),
                ('from_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_facility', to='billing.facility')),
            ],
            options={
                'verbose_name': 'Load',
                'verbose_name_plural': 'Loads',
                'db_table': 'loads',
            },
        ),
        migrations.CreateModel(
            name='LoadProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Load Process',
                'verbose_name_plural': 'Load Processes',
                'db_table': 'load_processes',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.loadprocess')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'db_table': 'process_statuses',
            },
        ),
        migrations.CreateModel(
            name='LoadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.load')),
            ],
            options={
                'verbose_name': 'Load History',
                'verbose_name_plural': 'Load Histories',
                'db_table': 'load_history',
            },
        ),
        migrations.CreateModel(
            name='LoadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='loads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.load')),
            ],
            options={
                'verbose_name': 'Load File',
                'verbose_name_plural': 'Load Files',
                'db_table': 'load_files',
            },
        ),
        migrations.AddField(
            model_name='load',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.loadprocess'),
        ),
        migrations.AddField(
            model_name='load',
            name='to_facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_facility', to='billing.facility'),
        ),
        migrations.CreateModel(
            name='FacilityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.facility')),
            ],
            options={
                'verbose_name': 'Facility History',
                'verbose_name_plural': 'Facility Histories',
                'db_table': 'facility_history',
            },
        ),
        migrations.CreateModel(
            name='BrokerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.broker')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broker History',
                'verbose_name_plural': 'Broker Histories',
                'db_table': 'broker_history',
            },
        ),
    ]
