# Generated by Django 4.2 on 2024-11-04 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='to_facility',
        ),
        migrations.CreateModel(
            name='LoadStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('destination', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.facility')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.load')),
            ],
            options={
                'verbose_name': 'Load Stop',
                'verbose_name_plural': 'Load Stops',
                'db_table': 'load_stops',
                'unique_together': {('load', 'order')},
            },
        ),
    ]
