# Generated by Django 4.2 on 2024-11-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverstatus',
            options={'ordering': ['id'], 'verbose_name_plural': ' Driver Statuses'},
        ),
        migrations.AlterModelOptions(
            name='truckstatus',
            options={'ordering': ['id'], 'verbose_name_plural': 'Truck Statuses'},
        ),
        migrations.AlterModelOptions(
            name='userstatus',
            options={'ordering': ['id'], 'verbose_name': 'Status', 'verbose_name_plural': ' User Statuses'},
        ),
    ]
